language: php

php:
  - 7.0
  - 7.1

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install

script: vendor/bin/phpunit